"""
Build Fixer Crew — CrewAI fallback for unresolvable build errors.

Triggered ONLY when the deterministic pipeline healer (Stage 4b) fails after
all retries.  Unlike the pipeline healer, this crew has **full repo access**:
it can read any file, write any file, and iterate until the build passes.

Architecture:
  Pipeline (Stage 3)  →  Stage 4b healer  →  BuildFixerCrew (fallback)
       80% of tasks           15%                    5%

The crew reuses the same agents (agents.py), task templates (tasks.py), and
tools (tools/) as ImplementCrew but is scoped to a single container and a
single goal: make the build green.

Flow:
  1. Developer agent reads error files (including out-of-scope ones)
  2. Developer fixes files via write_code() (no scope restriction)
  3. DevOps agent runs the build
  4. If still failing, loop back (max iterations)
  5. Return new/modified GeneratedFile objects + ContainerBuildResult
"""

import re
import time
from pathlib import Path

from crewai import Agent, Crew, Process, Task
from crewai.mcp import MCPServerStdio

from ...shared.paths import CHROMA_DIR
from ...shared.utils.llm_factory import create_llm
from ...shared.utils.logger import setup_logger
from ...shared.utils.tool_guardrails import install_guardrails, uninstall_guardrails
from .agents import AGENT_CONFIGS
from .schemas import (
    CodegenPlanInput,
    ContainerBuildResult,
    GeneratedFile,
)
from .tasks import build_fixer_fix_task, build_fixer_verify_task
from .tools import (
    BuildErrorParserTool,
    BuildRunnerTool,
    CodeReaderTool,
    CodeWriterTool,
    FactsQueryTool,
    RAGQueryTool,
)

logger = setup_logger(__name__)

_MCP_SERVER_PATH = str(Path(__file__).resolve().parents[4] / "mcp_server.py")
_MAX_FIXER_ITERATIONS = 3
_MAX_RPM = 30


class BuildFixerCrew:
    """CrewAI crew that fixes build errors the pipeline healer could not resolve.

    Key difference from pipeline healer:
    - Full repo read/write access (no fixed scope)
    - Agent-driven discovery of cascading breakage
    - Iterative build-fix loop with tool access
    """

    def __init__(
        self,
        repo_path: str,
        facts_path: str,
        chroma_dir: str | None = None,
    ):
        self.repo_path = Path(repo_path)
        self.facts_path = Path(facts_path)
        self.chroma_dir = chroma_dir or CHROMA_DIR
        self.total_calls = 0
        self.total_tokens = 0

    def run(
        self,
        container_id: str,
        container_name: str,
        build_command: str,
        plan_input: CodegenPlanInput,
        existing_generated: list[GeneratedFile],
        last_build_errors: str,
    ) -> tuple[list[GeneratedFile], ContainerBuildResult]:
        """Run the fixer crew for a single container.

        Args:
            container_id: e.g. "container.frontend"
            container_name: e.g. "frontend"
            build_command: Shell command that was used for building
            plan_input: The plan context (task_id, summary, upgrade_plan)
            existing_generated: Files already generated by Stage 3 + pipeline healer
            last_build_errors: Raw error output from the last failed build

        Returns:
            Tuple of (additional GeneratedFile list, ContainerBuildResult).
        """
        logger.info("")
        logger.info("=" * 60)
        logger.info(f"[BuildFixer] Starting for {container_name} ({container_id})")
        logger.info(f"[BuildFixer] Task: {plan_input.task_id} — {plan_input.summary}")
        logger.info("=" * 60)

        start_time = time.time()

        # Pre-populate staging with existing generated files so the build tool
        # applies them before running the build.
        staging: dict = {}
        for gf in existing_generated:
            staging[gf.file_path] = {
                "content": gf.content,
                "action": gf.action,
                "original_content": gf.original_content,
                "language": gf.language,
            }

        # Track which files the fixer adds (not in original scope)
        original_paths = set(staging.keys())

        for iteration in range(1, _MAX_FIXER_ITERATIONS + 1):
            logger.info(f"[BuildFixer] Iteration {iteration}/{_MAX_FIXER_ITERATIONS}")

            # Step 1: Developer fixes errors
            self._run_fix_iteration(
                container_name=container_name,
                container_id=container_id,
                plan_input=plan_input,
                staging=staging,
                build_errors=last_build_errors,
                iteration=iteration,
            )

            # Step 2: DevOps runs build
            build_passed, build_output = self._run_build_check(
                container_name=container_name,
                container_id=container_id,
                staging=staging,
                iteration=iteration,
            )

            if build_passed:
                duration = time.time() - start_time
                logger.info(f"[BuildFixer] BUILD PASSED after {iteration} iteration(s) ({duration:.1f}s)")

                new_files = self._extract_new_files(staging, original_paths)
                return new_files, ContainerBuildResult(
                    container_id=container_id,
                    container_name=container_name,
                    build_command=build_command,
                    success=True,
                    exit_code=0,
                    attempts=iteration,
                    healed_files=[gf.file_path for gf in new_files],
                    duration_seconds=round(duration, 1),
                )

            # Update errors for next iteration
            last_build_errors = build_output

        # All iterations exhausted
        duration = time.time() - start_time
        logger.warning(f"[BuildFixer] FAILED after {_MAX_FIXER_ITERATIONS} iterations ({duration:.1f}s)")

        new_files = self._extract_new_files(staging, original_paths)
        return new_files, ContainerBuildResult(
            container_id=container_id,
            container_name=container_name,
            build_command=build_command,
            success=False,
            exit_code=-1,
            error_summary=last_build_errors[-2000:],
            attempts=_MAX_FIXER_ITERATIONS,
            healed_files=[gf.file_path for gf in new_files],
            duration_seconds=round(duration, 1),
        )

    # =========================================================================
    # INTERNAL: Developer fix iteration
    # =========================================================================

    def _run_fix_iteration(
        self,
        container_name: str,
        container_id: str,
        plan_input: CodegenPlanInput,
        staging: dict,
        build_errors: str,
        iteration: int,
    ) -> None:
        """Run the developer agent to fix build errors."""
        description, expected_output = build_fixer_fix_task(
            container_name=container_name,
            container_id=container_id,
            plan=plan_input,
            staged_files=list(staging.keys()),
            build_errors=build_errors,
            iteration=iteration,
            max_iterations=_MAX_FIXER_ITERATIONS,
        )

        dev_tools = [
            CodeReaderTool(repo_path=str(self.repo_path)),
            CodeWriterTool(repo_path=str(self.repo_path), staging=staging),
            FactsQueryTool(facts_dir=str(self.facts_path.parent)),
            RAGQueryTool(chroma_dir=self.chroma_dir),
        ]

        dev = Agent(
            role=AGENT_CONFIGS["senior_developer"]["role"],
            goal="Fix all build errors, including in files outside the original scope.",
            backstory=AGENT_CONFIGS["senior_developer"]["backstory"],
            llm=create_llm(),
            tools=dev_tools,
            mcps=[MCPServerStdio(command="python", args=[_MCP_SERVER_PATH], cache_tools_list=True)],
            verbose=True,
            max_iter=30,
            max_retry_limit=3,
            allow_delegation=False,
            respect_context_window=True,
        )

        task = Task(description=description, expected_output=expected_output, agent=dev, human_input=False)

        tracker = None
        try:
            crew = Crew(
                agents=[dev],
                tasks=[task],
                process=Process.sequential,
                verbose=True,
                memory=False,
                max_rpm=_MAX_RPM,
                planning=False,
            )
            tracker = install_guardrails(max_total=60)
            result = crew.kickoff()

            tokens = getattr(result, "token_usage", {})
            crew_tokens = tokens.get("total_tokens", 0) if isinstance(tokens, dict) else 0
            self.total_tokens += crew_tokens
            self.total_calls += 1

            logger.info(f"[BuildFixer] Fix iteration {iteration} complete ({crew_tokens} tokens)")

        except Exception as e:
            logger.error(f"[BuildFixer] Fix iteration {iteration} failed: {e}")

        finally:
            uninstall_guardrails(tracker)

    # =========================================================================
    # INTERNAL: Build check iteration
    # =========================================================================

    def _run_build_check(
        self,
        container_name: str,
        container_id: str,
        staging: dict,
        iteration: int,
    ) -> tuple[bool, str]:
        """Run the DevOps agent to verify the build."""
        description, expected_output = build_fixer_verify_task(
            container_name=container_name,
            container_id=container_id,
            iteration=iteration,
        )

        devops_tools = [
            BuildRunnerTool(
                repo_path=str(self.repo_path),
                facts_path=str(self.facts_path),
                staging=staging,
            ),
            BuildErrorParserTool(),
        ]

        devops = Agent(
            role=AGENT_CONFIGS["devops_engineer"]["role"],
            goal="Run the build and report results.",
            backstory=AGENT_CONFIGS["devops_engineer"]["backstory"],
            llm=create_llm(),
            tools=devops_tools,
            mcps=[MCPServerStdio(command="python", args=[_MCP_SERVER_PATH], cache_tools_list=True)],
            verbose=True,
            max_iter=10,
            max_retry_limit=3,
            allow_delegation=False,
            respect_context_window=True,
        )

        task = Task(description=description, expected_output=expected_output, agent=devops, human_input=False)

        tracker = None
        build_output = ""
        build_passed = False

        try:
            crew = Crew(
                agents=[devops],
                tasks=[task],
                process=Process.sequential,
                verbose=True,
                memory=False,
                max_rpm=_MAX_RPM,
                planning=False,
            )
            tracker = install_guardrails(max_total=20)
            result = crew.kickoff()

            tokens = getattr(result, "token_usage", {})
            crew_tokens = tokens.get("total_tokens", 0) if isinstance(tokens, dict) else 0
            self.total_tokens += crew_tokens
            self.total_calls += 1

            result_text = str(result)
            build_output = result_text
            build_passed = self._check_build_result(result_text)

            logger.info(
                f"[BuildFixer] Build check {iteration}: "
                f"{'PASSED' if build_passed else 'FAILED'}"
            )

        except Exception as e:
            logger.error(f"[BuildFixer] Build check {iteration} failed: {e}")
            build_output = str(e)

        finally:
            uninstall_guardrails(tracker)

        return build_passed, build_output

    # =========================================================================
    # HELPERS
    # =========================================================================

    @staticmethod
    def _check_build_result(result_text: str) -> bool:
        """Parse agent output to determine build success."""
        text = result_text.lower()
        for pattern in (
            r"build_passed\s*[:=]\s*true",
            r"success\s*[:=]\s*true",
            r"build\s+passed",
            r"build\s+successful",
            r"exit_code\s*[:=]\s*0",
        ):
            if re.search(pattern, text):
                return True
        return False

    @staticmethod
    def _extract_new_files(staging: dict, original_paths: set[str]) -> list[GeneratedFile]:
        """Extract files added by the fixer (not in original scope)."""
        new_files = []
        for file_path, entry in staging.items():
            if file_path not in original_paths:
                content = entry.get("content", "") if isinstance(entry, dict) else str(entry)
                action = entry.get("action", "modify") if isinstance(entry, dict) else "modify"
                original = entry.get("original_content", "") if isinstance(entry, dict) else ""
                language = entry.get("language", "other") if isinstance(entry, dict) else "other"

                new_files.append(
                    GeneratedFile(
                        file_path=file_path,
                        content=content,
                        original_content=original,
                        action=action,
                        confidence=0.6,
                        language=language,
                    )
                )
        return new_files
